//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.10 at 02:01:51 PM CST 
//


package com.page.pagetop.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NotificationMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotificationMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OutBoundChannel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BccAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CcAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FromAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReplyToAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ToAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MessageBody" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificationMessage", propOrder = {
    "outBoundChannel",
    "bccAddress",
    "ccAddress",
    "fromAddress",
    "replyToAddress",
    "subject",
    "toAddress",
    "messageBody"
})
@XmlRootElement(name = "NotificationMessage")
public class NotificationMessage {

    @XmlElement(name = "OutBoundChannel", required = true)
    protected String outBoundChannel;
    @XmlElement(name = "BccAddress", required = true)
    protected String bccAddress;
    @XmlElement(name = "CcAddress", required = true)
    protected String ccAddress;
    @XmlElement(name = "FromAddress", required = true)
    protected String fromAddress;
    @XmlElement(name = "ReplyToAddress", required = true)
    protected String replyToAddress;
    @XmlElement(name = "Subject", required = true)
    protected String subject;
    @XmlElement(name = "ToAddress", required = true)
    protected String toAddress;
    @XmlElement(name = "MessageBody", required = true)
    protected String messageBody;

    /**
     * Gets the value of the outBoundChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutBoundChannel() {
        return outBoundChannel;
    }

    /**
     * Sets the value of the outBoundChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutBoundChannel(String value) {
        this.outBoundChannel = value;
    }

    /**
     * Gets the value of the bccAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBccAddress() {
        return bccAddress;
    }

    /**
     * Sets the value of the bccAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBccAddress(String value) {
        this.bccAddress = value;
    }

    /**
     * Gets the value of the ccAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcAddress() {
        return ccAddress;
    }

    /**
     * Sets the value of the ccAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcAddress(String value) {
        this.ccAddress = value;
    }

    /**
     * Gets the value of the fromAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromAddress() {
        return fromAddress;
    }

    /**
     * Sets the value of the fromAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromAddress(String value) {
        this.fromAddress = value;
    }

    /**
     * Gets the value of the replyToAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyToAddress() {
        return replyToAddress;
    }

    /**
     * Sets the value of the replyToAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyToAddress(String value) {
        this.replyToAddress = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the toAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToAddress() {
        return toAddress;
    }

    /**
     * Sets the value of the toAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToAddress(String value) {
        this.toAddress = value;
    }

    /**
     * Gets the value of the messageBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageBody() {
        return messageBody;
    }

    /**
     * Sets the value of the messageBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageBody(String value) {
        this.messageBody = value;
    }

}
