//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.10 at 02:01:51 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mypage.com/NotificationMessage", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.page.pagetop.service;
